In [1]:
## import basic libraries to handle data
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
## import data
iris_data = pd.read_csv('https://raw.githubusercontent.com/mwaskom/seaborn-data/master/iris.csv')
iris_data.head(5)

sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [3]:
## Explore data
np_iris_data = np.array(iris_data)
print(np_iris_data[0:5,:])

[[5.1 3.5 1.4 0.2 'setosa']
 [4.9 3.0 1.4 0.2 'setosa']
 [4.7 3.2 1.3 0.2 'setosa']
 [4.6 3.1 1.5 0.2 'setosa']
 [5.0 3.6 1.4 0.2 'setosa']]


In [4]:
datax = np_iris_data[:, 0:4]
datay = np_iris_data[:, -1]

print(datax[0:5,:])
print(datay[0:10])

[[5.1 3.5 1.4 0.2]
 [4.9 3.0 1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.0 3.6 1.4 0.2]]
['setosa' 'setosa' 'setosa' 'setosa' 'setosa' 'setosa' 'setosa' 'setosa'
 'setosa' 'setosa']


In [5]:
from sklearn.model_selection import train_test_split
trnx, tstx, trny, tsty = train_test_split(datax, datay, test_size=0.3)
print(trnx.shape, tstx.shape, trny.shape, tsty.shape)

(105, 4) (45, 4) (105,) (45,)


In [6]:
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
scaler.fit(trnx)
trnx_scale = scaler.transform(trnx)
tstx_scale = scaler.transform(tstx)
print(np.min(trnx_scale[:, 0]), np.max(trnx_scale[:, 0]))
print(np.min(tstx_scale[:, 0]), np.max(tstx_scale[:, 0]))

0.0 1.0
-0.028571428571428692 0.9428571428571426


In [7]:
from sklearn.neural_network import MLPClassifier

clf = MLPClassifier(hidden_layer_sizes=(10, ), max_iter=500)
clf.fit(trnx, trny)
tsty_hat = clf.predict(tstx)

C:\Users\chopper\anaconda3\envs\machinelearning\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:696: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  ConvergenceWarning,


In [8]:
print(clf)
print(tsty[0:10])
print(tsty_hat[0:10])

MLPClassifier(hidden_layer_sizes=(10,), max_iter=500)
['virginica' 'setosa' 'versicolor' 'setosa' 'setosa' 'versicolor' 'setosa'
 'setosa' 'virginica' 'versicolor']
['virginica' 'setosa' 'versicolor' 'setosa' 'setosa' 'versicolor' 'setosa'
 'setosa' 'virginica' 'versicolor']


In [9]:
clf2 = MLPClassifier(hidden_layer_sizes=(10, 15, 10,), max_iter=500)
clf2.fit(trnx, trny)
tsty_hat2 = clf2.predict(tstx)
print(tsty[0:10])
print(tsty_hat2[0:10])

['virginica' 'setosa' 'versicolor' 'setosa' 'setosa' 'versicolor' 'setosa'
 'setosa' 'virginica' 'versicolor']
['virginica' 'setosa' 'versicolor' 'setosa' 'setosa' 'versicolor' 'setosa'
 'setosa' 'virginica' 'versicolor']


In [10]:
from sklearn.metrics import accuracy_score
print(accuracy_score(tsty, tsty_hat), accuracy_score(tsty, tsty_hat2))

0.9777777777777777 0.9555555555555556


In [11]:
# SVM
from sklearn.svm import SVC
svc_model = SVC(C=100, kernel='rbf', degree=3, gamma=0.1, coef0=0.0, shrinking=True, probability=True, tol=0.001, cache_size=200, class_weight=None, verbose=False, max_iter=-1, decision_function_shape='ovr', random_state=None)
# svc_model = SVC()
svc_model.fit(X=trnx, y=trny)
tsty_hat = svc_model.predict(tstx)
accuracy_score(tsty, tsty_hat)

0.9555555555555556

In [12]:
print(tsty)
print(tsty_hat)

['virginica' 'setosa' 'versicolor' 'setosa' 'setosa' 'versicolor' 'setosa'
 'setosa' 'virginica' 'versicolor' 'virginica' 'setosa' 'virginica'
 'virginica' 'virginica' 'setosa' 'versicolor' 'virginica' 'setosa'
 'versicolor' 'virginica' 'versicolor' 'virginica' 'virginica'
 'versicolor' 'setosa' 'virginica' 'versicolor' 'virginica' 'virginica'
 'virginica' 'setosa' 'setosa' 'virginica' 'versicolor' 'virginica'
 'setosa' 'setosa' 'virginica' 'setosa' 'virginica' 'setosa' 'setosa'
 'versicolor' 'versicolor']
['virginica' 'setosa' 'versicolor' 'setosa' 'setosa' 'versicolor' 'setosa'
 'setosa' 'virginica' 'versicolor' 'virginica' 'setosa' 'virginica'
 'virginica' 'virginica' 'setosa' 'versicolor' 'virginica' 'setosa'
 'versicolor' 'virginica' 'versicolor' 'virginica' 'virginica'
 'versicolor' 'setosa' 'virginica' 'virginica' 'virginica' 'virginica'
 'virginica' 'setosa' 'setosa' 'virginica' 'virginica' 'virginica'
 'setosa' 'setosa' 'virginica' 'setosa' 'virginica' 'setosa' 'setosa'
 'vers

0.0

In [3]:
# Tensorflow keras sequential API
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

from tensorflow.keras import layers, models, optimizers

AttributeError: type object 'h5py.h5.H5PYConfig' has no attribute '__reduce_cython__'

In [3]:
input_shape = Input(shape=(4,))
mlp_model = Sequential()
mlp_model.add(layers.Dense(units=10, activation='relu', input_shape=input_shape))
mlp_model.add(layers.Dense(units=20, activation='relu'))
mlp_model.add(layers.Dense(units=10, activation='relu'))
mlp_model.add(layers.Dense(units=3, activation='softmax'))
mlp_model.compile(optimizers='Adam', loss='categorical_crossentropy', metrics='accuracy')
mlp_model.summary()

AttributeError: module 'keras.api._v2.keras' has no attribute 'Input'